name: Generate Snake

on:
  schedule:
    # Executa a cada 24 horas
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Clona o repositório
      - uses: actions/checkout@v3

      # Gera a cobrinha (snake) com base nos commits
      - uses: Platane/snk@v3
        with:
          github_user_name: gregoriLima
          outputs: |
            dist/github-snake.svg
            dist/github-snake.gif

      # Publica na branch `output`
      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
